### ISSUE TITLE
レジュメページの表示崩れ

### ISSUE THREAD

**Issue by MaxEzaki** [MaxEzaki/maxezaki-portal-website#17]
![CleanShot 2022-10-27 at 10 37 50](https://user-images.githubusercontent.com/38445069/198170814-3a0ed914-c164-47d5-badf-dfed169d5ac6.png)
こんなんなっちゃう
左カラムに影響あるので、下記のスタイルを追加しておく
```css

.c4cy6g5 {
    background-color: #414141;
    width: 20%;
    padding: 2em;
    color: #fff;
    height: calc(100vh - 65px - 84px); // 追加
    overflow: scroll; // 追加
}

```

![CleanShot 2022-10-27 at 10 35 19](https://user-images.githubusercontent.com/38445069/198170562-9adfc1ee-5380-4131-ba17-a9b0b3b7c568.png)

_Originally posted by @MaxEzaki in https://github.com/MaxEzaki/maxezaki-portal-website/issues/6#issuecomment-1292853652_
